CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR (30),
    pass_hash VARCHAR (256),
    email VARCHAR (30),
    reg_date DATETIME DEFAULT CURRENT_TIMESTAMP
    );


CREATE TABLE IF NOT EXISTS posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR (200),
    post_slug VARCHAR (40),
    post_text VARCHAR,
    post_date DATETIME DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS feedbacks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR (30),
    email VARCHAR (51),
    message VARCHAR,
    feed_date DATETIME DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS comments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR (30),
    text VARCHAR,
    date_add DATETIME DEFAULT CURRENT_TIMESTAMP,
    post_id INTEGER,
    FOREIGN KEY(post_id) REFERENCES posts(id)
);

CREATE TABLE IF NOT EXISTS admins (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR (30),
    pass_hash VARCHAR (256)
    );